spring:
  application:
    name: code-microservice-webui

server:
  port: 8094

eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
  client:
    registerWithEureka: false #是否向服务注册中心注册自己 false
    fetchRegistry: true #是否检索服务 false
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/

# ribbon.eureka.enabled: true



feign:
  e-commerce-order: e-commerce-cloud
  e-commerce-goods: e-commerce-cloud