spring:
  application:
    name: code-microservice-cloud

server:
  port: 8090

eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
  client:
    registerWithEureka: true #是否向服务注册中心注册自己 false
    fetchRegistry: true #是否检索服务 false
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

feign-qualifier:
#feign-client-qualifier-end
